spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ms-tournament
          uri: http://localhost:9090
          predicates:
          - Path=/api/tournaments/**
        - id: ms-football-team
          uri: http://localhost:9091
          predicates:
          - Path=/api/football-teams/**
        - id: ms-match
          uri: http://localhost:9092
          predicates:
            - Path=/api/matches/**
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

server:
  port: 8095